// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0pvGkBHixl_kiahA8YHpyfE0QLDSIGI',
    appId: '1:499795686268:android:31cc99327add9792eeeaf9',
    messagingSenderId: '499795686268',
    projectId: 'flutter-spotify-firebase',
    databaseURL: 'https://flutter-spotify-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-spotify-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_G_BDACM7XbG57WX-sF7esyefQp03IEg',
    appId: '1:499795686268:ios:6ee9e8c5925165ceeeeaf9',
    messagingSenderId: '499795686268',
    projectId: 'flutter-spotify-firebase',
    databaseURL: 'https://flutter-spotify-firebase-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-spotify-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterSpotify',
  );
}
